#!/bin/bash

echo "=========================================="
echo "Ejercicio 1: Consultas Básicas"
echo "=========================================="
echo ""

echo "Para ejecutar en PostgreSQL:"
echo "1. Conectar a PostgreSQL:"
echo "   psql -U postgres"
echo ""
echo "2. Crear base de datos:"
echo "   CREATE DATABASE tienda_db;"
echo "   \\c tienda_db"
echo ""
echo "3. Ejecutar el schema:"
echo "   \\i schema.sql"
echo ""
echo "4. Ejecutar consultas:"
echo "   \\i consultas.sql"
echo ""
echo "O usar Docker:"
echo "   docker run -d --name postgres -e POSTGRES_PASSWORD=secret postgres:15"
echo "   docker exec -it postgres psql -U postgres"
