#!/bin/bash

echo "=========================================="
echo "Guía de Comandos Kubernetes"
echo "=========================================="
echo ""

echo "=== Gestión de Pods ==="
echo "kubectl get pods                    # Listar pods"
echo "kubectl get pods -o wide            # Listar pods con más detalles"
echo "kubectl describe pod <nombre>       # Describir pod"
echo "kubectl logs <nombre>               # Ver logs"
echo "kubectl logs -f <nombre>            # Logs en tiempo real"
echo "kubectl exec -it <nombre> -- sh     # Acceder al pod"
echo "kubectl delete pod <nombre>         # Eliminar pod"
echo ""

echo "=== Gestión de Deployments ==="
echo "kubectl get deployments             # Listar deployments"
echo "kubectl describe deployment <nombre>"
echo "kubectl apply -f archivo.yaml        # Aplicar configuración"
echo "kubectl scale deployment <nombre> --replicas=5"
echo "kubectl set image deployment/<nombre> app=imagen:v2"
echo "kubectl rollout status deployment/<nombre>"
echo "kubectl rollout undo deployment/<nombre>"
echo ""

echo "=== Gestión de Servicios ==="
echo "kubectl get services                # Listar servicios"
echo "kubectl describe service <nombre>"
echo "kubectl expose pod <nombre> --port=80 --type=NodePort"
echo "kubectl delete service <nombre>"
echo ""

echo "=== Gestión de Ingress ==="
echo "kubectl get ingress                 # Listar ingress"
echo "kubectl describe ingress <nombre>"
echo ""

echo "=== Gestión de ConfigMaps y Secrets ==="
echo "kubectl get configmaps"
echo "kubectl get secrets"
echo "kubectl create configmap app-config --from-literal=ENV=prod"
echo "kubectl create secret generic app-secret --from-literal=KEY=value"
echo ""

echo "=== Herramientas de debug ==="
echo "kubectl get events                   # Ver eventos"
echo "kubectl top pods                     # Uso de recursos"
echo "kubectl cluster-info                 # Info del cluster"
echo "kubectl get nodes                    # Ver nodos"
