version: '3.8'

services:
  app:
    image: node:18-alpine
    container_name: mi-node-app
    command: sh -c "echo 'Node.js app iniciada' && tail -f /dev/null"
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: mi-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
